### ISSUE TITLE
BDC PWM control exceeding limits?

### ISSUE THREAD

**Issue by bit-pirate** [synapticon/sc_sncn_motorcontrol#1]
Looking at the [logic of the PWM controller converting the control voltage to PWM settings](https://github.com/synapticon/sc_sncn_motorcontrol/blob/master/module_brushed_dc/src/brushed_dc_server.xc#L40-L79), I'm wondering if there is a bug or I'm just not comprehending it fully. I understand it as follows:

`voltage` is mapped onto PWM settings for each phase using the follow limits:
`PWM_MIN_LIMIT` = 250
`PWM_MAX_VALUE` = 13889
`PWM_DEAD_TIME` = 300
`BDC_PWM_CONTROL_LIMIT` = 13589 (= `PWM_MAX_VALUE - PWM_DEAD_TIME`)
`pwm_half` = `(PWM_MAX_VALUE - PWM_DEAD_TIME) >> 1` = 6794 (= `BDC_PWM_CONTROL_LIMIT`/2)

Now looking at the if else parts,

```
if(voltage <= pwm_half)
                {
                    pwm[0] = pwm_half + voltage;
                    pwm[1] = pwm_half;
                }
                else if(voltage > pwm_half && voltage < BDC_PWM_CONTROL_LIMIT)
                {
                    pwm[0] = pwm_half + pwm_half;
                    pwm[1] = pwm_half - (voltage - pwm_half);
                }
                else if(voltage >= BDC_PWM_CONTROL_LIMIT)
                {
                    pwm[0] = pwm_half + pwm_half;
                    pwm[1] = PWM_MIN_LIMIT;
                }
```

`pwm[1]` in `else if(voltage > pwm_half && voltage < BDC_PWM_CONTROL_LIMIT)` can actually reach a value below `PWM_MIN_LIMIT` (as set in the next case), since `pwm_half - (voltage - pwm_half)` can get as low as `1`:

```
pwm[1] = pwm_half - (voltage - pwm_half);
pwm[1] = 2 * pwm_half - voltage;
```

with voltage = BDC_PWM_CONTROL_LIMIT - 1 and pwm_half = BDC_PWM_CONTROL_LIMIT / 2

```
pwm[1] = BDC_PWM_CONTROL_LIMIT - BDC_PWM_CONTROL_LIMIT + 1;
pwm[1] = 1;
```

Is this intended? Is there a problem setting `pwm[1]` << `PWM_MIN`?

**Comment by agus-xyz** [comment]
Hi Marcus,

First, thanks a lot for your feedback!! :D

you are certainly right about this wrong behavior when calculating the voltages, and it should be fixed. Nevertheless, the fix will not make (I guess) a huge difference on the behavior of the motor and definitely the hardware is safe since this values are later on double checked at the pwm client before updating the pwm output. Nothing will exceeds the limits defined at the pwm config file.

Best!

**Comment by vtretyakov** [comment]
With the new module_pwm release I am closing this issue.
